FROM rust:1.64 AS builder
WORKDIR /app
COPY . .
RUN cargo build --release

FROM gcr.io/distroless/cc-debian11
COPY --from=builder /app/target/release/tp-01 /runnable/tp-01
WORKDIR /runnable
ENTRYPOINT ["./tp-01"]